[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "whosYourAgent"
version = "0.0.1"
requires-python = ">=3.7"
dependencies = ["requests",
                "bs4"]